### PR TITLE
Add sym/cmp/pkg/dev for ESP-12S module

### PR DESCRIPTION
**Pull request by dbrgn**
Datasheet: https://www.elecrow.com/download/ESP-12S_User_Manual.pdf

One of the more widely used ESP modules, e.g. by Adafruit: https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/overview

Footprint:

img

### CODE REVIEW

**Comment by dbrgn** [comment]
On the bottom there's a pad that looks like it could be soldered: 

image

However, the datasheet doesn't mention any dimensions, so I can't add it.

**Comment by ubruhin** [comment]
I'm still not sure how we should handle the name of manufacturer specific library elements... Maybe sym/cmp/dev should be named "Ai-Thinker ESP-12S" and the package "AI-THINKER_ESP-12S" or something like that? But actually the IPC7351 naming convention for manufacturer-specific packages doesn't make much sense IMHO. I mean, why should we use uppercase letters and underscores instead of spaces if our EDA tool has no issues with spaces or other special characters?

Apart from that, I saw that the device is in another category than the component, which doesn't make sense IMO.

**Comment by dbrgn** [comment]
> I mean, why should we use uppercase letters and underscores instead of spaces if our EDA tool has no issues with spaces or other special characters?

Not sure, probably for consistency with other tools. Also, practically all generic packages (e.g. SOIC, DFN, BGA etc) have capitalized abbreviations, so it might look more consistent within the parts list as well if everything's capitalized.

I'd be open to replace underscores with spaces though, might be easier to read.

Edit: I'll create a thread in the forum.
Edit2: Done: https://librepcb.discourse.group/t/naming-of-packages/167

**Review by ubruhin — APPROVED** [review]
Fixing the inconsistent categories of component and device would be nice. But not critical, so let's approve this ;)

**Pull request merged**
